export const fakePolitico0 = {id: 0, nome: 'NOME DO POLITICO', idade: 'IDADE', cargo: 'CARGO E LOCALIZACAO', vigencia: 'VIGENCIA DO CARGO', partido: 'NOME DO PARTIDO', vote: 'xxxx', ranking: '1', approval: '30'};
export const fakePolitico1 = {id: 1, nome: 'Helder', idade: '30 anos', cargo: 'Presidente', vigencia: '29 de julho de 2005 a 24 de janeiro de 2012', partido: 'Partido XYZ', vote: '1234', ranking: '10', approval: '50'};
export const fakePolitico2 = {id: 2, nome: 'Marcela', idade: '24 anos', cargo: 'Prefeito de São Paulo', vigencia: '1º de janeiro de 2013 até a atualidade', partido: 'Partido ABC', vote: '0987', ranking: '121', approval: '0'};
export const fakePoliticos = [fakePolitico0, fakePolitico1, fakePolitico2, fakePolitico1,fakePolitico2, fakePolitico1,fakePolitico2, fakePolitico1,fakePolitico2, fakePolitico1,fakePolitico2, fakePolitico1,fakePolitico2, fakePolitico1,fakePolitico2, fakePolitico1,fakePolitico2, fakePolitico1,fakePolitico2, fakePolitico1,fakePolitico2, fakePolitico1,fakePolitico2, fakePolitico1];

export const fakeFilter = [{topic: 'Localização', options: ['São Paulo', 'Rio de Janeiro']}, 
						   {topic: 'Cargo', options: ['Prefeito', 'Vereador']},
						   {topic: 'Partido', options: ['PT', 'PSDB', 'PSOL']}, 
						   {topic: 'Assunto', options: ['Saúde', 'Educação', 'Transporte', 'Animais']},
						   {topic: 'Aprovação', options: ['Melhores Aprovados', 'Piores Aprovados']}];

export const fakeProposta0 = {id: 0, nome: 'NOME DA PROPOSTA', data: 'dd/mm/AA', categoria: 'CATEGORIA', ranking: '1', approval: '70', nomePolitico: 'NOME DO POLITICO', politicoID: 0,
descricao: 'Lorem ipsum dolor sit amet, pro erant dicunt ancillae in, et summo ludus nonumes vis, at deleniti lobortis comprehensam vim. Ne quem modo labore est. Id wisi albucius mandamus eam, dolorem adolescens ex est. Cu has vide intellegam, pri brute legere ut, eum brute vivendo conceptam ea. Sed quot percipitur scripserit et, in apeirian repudiare omittantur duo.'};
export const fakeProposta1 = {id: 1, nome: 'Transporte de animais na cabine de passageiro', data: '13/10/16', categoria: 'Ambiente', ranking: '10', approval: '40', nomePolitico: 'Helder', politicoID: 1,
descricao: 'Lorem ipsum dolor sit amet, pro erant dicunt ancillae in, et summo ludus nonumes vis, at deleniti lobortis comprehensam vim. Ne quem modo labore est. Id wisi albucius mandamus eam, dolorem adolescens ex est. Cu has vide intellegam, pri brute legere ut, eum brute vivendo conceptam ea. Sed quot percipitur scripserit et, in apeirian repudiare omittantur duo.'};
export const fakeProposta2 = {id: 2, nome: 'Regulamentação de aplicativos de transporte (Uber)', data: '02/11/16', categoria: 'Transporte', ranking: '121', approval: '90', nomePolitico: 'Marcela', politicoID: 2,
descricao: 'Lorem ipsum dolor sit amet, pro erant dicunt ancillae in, et summo ludus nonumes vis, at deleniti lobortis comprehensam vim. Ne quem modo labore est. Id wisi albucius mandamus eam, dolorem adolescens ex est. Cu has vide intellegam, pri brute legere ut, eum brute vivendo conceptam ea. Sed quot percipitur scripserit et, in apeirian repudiare omittantur duo.'};
export const fakePropostas = [fakeProposta0, fakeProposta1, fakeProposta2, fakeProposta1,fakeProposta2, fakeProposta1,fakeProposta2, fakeProposta1,fakeProposta2, fakeProposta1,fakeProposta2, fakeProposta1,fakeProposta2, fakeProposta1,fakeProposta2, fakeProposta1,fakeProposta2, fakeProposta1,fakeProposta2, fakeProposta1,fakeProposta2, fakeProposta1,fakeProposta2, fakeProposta1];